# Generated by Django 5.0 on 2024-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_followers_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.IntegerField(blank=True, default=0, verbose_name='following'),
        ),
    ]
