# Generated by Django 5.0 on 2024-01-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bid', models.IntegerField(blank=True, default=0, verbose_name='starting_bid')),
                ('current_bid', models.IntegerField(blank=True, default=0, verbose_name='current_bid')),
                ('end_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=0, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
